### ISSUE TITLE
Check usage of User table

### ISSUE THREAD

**Issue by tuminoid** [tuminoid/kisakone#222]
Related to competitions, a Player table entry should be used instead of User. Check all usage cases, especially AJAX autocompletes.

**Comment by nixe-** [comment]
ie. in addcompetitor page when search is empty you call *$players = GetPlayerUsers($query, '', $has_pdga_number);* and that function makes queries to User table.

**Comment by tuminoid** [comment]
User and Player are in way too close symbiosis, and part of the data is duplicated, wrong place etc. 
They have to be rethought at some point. Being very central to everything, migration to any other scheme is going to be super hard. 

Closing this for now.
