### ISSUE TITLE
Ordering of competitions on events page

### ISSUE THREAD

**Issue by nixe-** [tuminoid/kisakone#268]
When you go to coming competitions page it's basicly fine, but when try to follow page with page monitor (diff) it's not working, or at least it's annoying. 
http://s28.postimg.org/pav8su1od/Sieppaa.png

I think query is not accurate, as competitions are not always in same order. So it might be good idea to add ie. ID to end of order clause so competitions came in same order every time. Didn't check code, so don't know how it's done, just suggesting.

**Comment by tuminoid** [comment]
Looks like competitions are ordered by `startdate`, and that leaves room for errors seen. I'll add some further ordering by `enddate` and then `id`, to get them sorted always the same.

**Comment by tuminoid** [comment]
Fixed in next.
